spring:
  cache:
    type: redis
#    cache-names:
#      - buckets
#      - buckets2
#    caffeine:
#      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters: # each config entry creates one servlet filter or other filter
    - cache-name: buckets # create new servlet filter with bucket4j configuration
      metrics:
        tags:
          - key: IP
            expression: getRemoteAddr()
            types: REJECTED_COUNTER # for data privacy reasons the IP should only be collected on bucket rejections
      url: /ping
      rate-limits:
        - expression: getHeader('X-api-key') # IP based filter
          bandwidths: # maximum of 5 requests within 10 seconds
            - capacity: 100
              time: 1
              unit: hours
    - cache-name: buckets2
      url: /pong
      rate-limits:
        - expression: getRemoteAddr() # IP based filter
          bandwidths: # maximum of 5 requests within 10 seconds
            - capacity: 100
              time: 10
              unit: seconds

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
